// Package gatewayconfig renders registered APIs into nginx configuration files
// on a shared volume that the gateway hot-reloads (watch mode). The API only
// writes files; the Nginx container detects changes and reloads itself.
package gatewayconfig

import (
	"context"
	"fmt"
	"net/url"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"go-enterprise-api/internal/domain/gatewayapi"
)

// Renderer writes nginx fragments for the gateway's registry.
type Renderer struct {
	// BaseDir is the api-side mount of the shared registry volume, e.g.
	// /app/gateway-configs. Subdirectories: zones.conf (http level),
	// locations/ (server/location level) and logs/ (per-api access logs).
	BaseDir string
	// AuthUpstream is where nginx reaches the API's internal auth endpoint
	// on the docker network, e.g. http://api:8080.
	AuthUpstream string
}

// gateway-side paths (nginx sees these, not the api-side BaseDir).
const (
	gatewayZonesInclude  = "/etc/nginx/registry/zones.conf"
	gatewayLogsDir       = "/etc/nginx/registry/logs"
	gatewayAuthEndpoint  = "/internal/auth"
	gatewayJSONLogFormat = "gateway_json"
)

func (r *Renderer) zonesFile() string    { return filepath.Join(r.BaseDir, "zones.conf") }
func (r *Renderer) locationsDir() string { return filepath.Join(r.BaseDir, "locations") }
func (r *Renderer) logsDir() string      { return filepath.Join(r.BaseDir, "logs") }

func (r *Renderer) locationFile(id int64) string {
	return filepath.Join(r.locationsDir(), fmt.Sprintf("reg_%d.conf", id))
}

func (r *Renderer) logFile(id int64) string {
	return filepath.Join(gatewayLogsDir, fmt.Sprintf("reg_%d.json", id))
}

// RenderZones emits the http-level limit_req_zone lines for active APIs.
func (r *Renderer) RenderZones(apis []gatewayapi.GatewayAPI) string {
	var b strings.Builder
	b.WriteString("# Generated by go-enterprise-api gateway registry. Do not edit.\n")
	sorted := append([]gatewayapi.GatewayAPI(nil), apis...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].ID < sorted[j].ID })
	for _, api := range sorted {
		if !api.IsActive {
			continue
		}
		fmt.Fprintf(&b, "limit_req_zone $binary_remote_addr zone=reg_%d_%d:2m rate=%dr/m;\n",
			api.ID, api.RateLimitRPM, api.RateLimitRPM)
	}
	return b.String()
}

// RenderLocation emits one server-level location block for a registered API.
func (r *Renderer) RenderLocation(api gatewayapi.GatewayAPI) (string, error) {
	origin, err := upstreamOrigin(api.Upstream)
	if err != nil {
		return "", err
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# reg_%d — %s (%s → %s)\n#   auth=%v rate=%dr/m methods=%s\n",
		api.ID, api.Name, api.BasePath, api.Upstream, api.RequiresAuth, api.RateLimitRPM, strings.Join(api.Methods, "|"))

	if api.RequiresAuth {
		fmt.Fprintf(&b, `
location = /_gw_auth_%d {
    internal;
    proxy_set_header Authorization $http_authorization;
    proxy_set_header X-Gateway-Token $gateway_token;
    proxy_pass %s%s;
}
`, api.ID, r.AuthUpstream, gatewayAuthEndpoint)
	}

	fmt.Fprintf(&b, `
location ^~ %s/ {
`, api.BasePath)

	if api.RequiresAuth {
		fmt.Fprintf(&b, "    auth_request /_gw_auth_%d;\n", api.ID)
	}
	fmt.Fprintf(&b, "    limit_req zone=reg_%d_%d burst=%d nodelay;\n",
		api.ID, api.RateLimitRPM, api.RateLimitRPM)

	methods := strings.Join(api.Methods, "|")
	if len(api.Methods) == 1 {
		fmt.Fprintf(&b, "    if ($request_method !~ ^%s$) { return 405; }\n", regexp.QuoteMeta(api.Methods[0]))
	} else {
		fmt.Fprintf(&b, "    if ($request_method !~ ^(%s)$) { return 405; }\n", methods)
	}

	fmt.Fprintf(&b, `
    rewrite ^%s$ / break;
    rewrite ^%s(/.*)$ $1 break;
    proxy_pass %s;
    access_log %s %s;
}
`, api.BasePath, api.BasePath, origin, r.logFile(api.ID), gatewayJSONLogFormat)

	return b.String(), nil
}

// Publisher re-applies the whole registry to the gateway by rendering the
// active APIs and handing them to the Renderer.
type Publisher struct {
	Renderer *Renderer
	Repo     gatewayapi.Repository
}

func NewPublisher(r *Renderer, repo gatewayapi.Repository) *Publisher {
	return &Publisher{Renderer: r, Repo: repo}
}

func (p *Publisher) Publish(ctx context.Context) error {
	apis, err := p.Repo.ListActive(ctx)
	if err != nil {
		return err
	}
	return p.Renderer.Publish(apis)
}

// Publish rewrites the registry files for the given (usually active) APIs:
// zones.conf is regenerated, each API gets locations/reg_<id>.conf, and stale
// files for removed/inactive APIs are deleted. The gateway hot-reloads it.
func (r *Renderer) Publish(apis []gatewayapi.GatewayAPI) error {
	if err := os.MkdirAll(r.locationsDir(), 0o755); err != nil {
		return err
	}
	if err := os.MkdirAll(r.logsDir(), 0o755); err != nil {
		return err
	}

	if err := atomicWrite(r.zonesFile(), []byte(r.RenderZones(apis))); err != nil {
		return err
	}

	active := make(map[int64]bool)
	for _, api := range apis {
		if !api.IsActive {
			continue
		}
		active[api.ID] = true
		content, err := r.RenderLocation(api)
		if err != nil {
			continue // invalid upstream — skip publishing but keep the row
		}
		if err := atomicWrite(r.locationFile(api.ID), []byte(content)); err != nil {
			return err
		}
	}

	// Remove location files for APIs that are inactive or no longer registered.
	entries, err := os.ReadDir(r.locationsDir())
	if err != nil && !os.IsNotExist(err) {
		return err
	}
	for _, e := range entries {
		var id int64
		if _, err := fmt.Sscanf(e.Name(), "reg_%d.conf", &id); err != nil || !active[id] {
			_ = os.Remove(filepath.Join(r.locationsDir(), e.Name()))
		}
	}
	return nil
}

func atomicWrite(path string, data []byte) error {
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, data, 0o644); err != nil {
		return err
	}
	return os.Rename(tmp, path)
}

var pathSegment = regexp.MustCompile(`^/[a-zA-Z0-9._~-]+$`)

// ValidateBasePath accepts a single-segment prefix like /orders.
func ValidateBasePath(p string) error {
	if !pathSegment.MatchString(p) {
		return gatewayapi.ErrInvalidBasePath
	}
	return nil
}

// upstreamOrigin strips the path from an upstream url, returning the nginx
// proxy_pass origin (the registered base_path is rewritten to the upstream
// root, so an upstream path would be silently dropped).
func upstreamOrigin(raw string) (string, error) {
	u, err := url.Parse(raw)
	if err != nil || u.Scheme == "" || u.Host == "" {
		return "", gatewayapi.ErrInvalidUpstream
	}
	if u.Scheme != "http" && u.Scheme != "https" {
		return "", gatewayapi.ErrInvalidUpstream
	}
	return u.Scheme + "://" + u.Host, nil
}
