apiVersion: v1
kind: Service
metadata:
  name: mock-idp
  namespace: go-enterprise
spec:
  selector:
    app: mock-idp
  ports:
    - port: 9090
      targetPort: 9090
      name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-idp
  namespace: go-enterprise
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mock-idp
  template:
    metadata:
      labels:
        app: mock-idp
    spec:
      containers:
        - name: mock-idp
          image: mock-idp:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
          readinessProbe:
            httpGet:
              path: /healthz
              port: 9090
              scheme: HTTP